inherit_from: .rubocop_todo.yml
require: rubocop-rspec
Bundler/OrderedGems:
  Enabled: true
Style/Documentation:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/Alias:
  EnforcedStyle: prefer_alias_method
Style/EmptyCaseCondition:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
  EnforcedStyle: scientific
Style/FrozenStringLiteralComment:
  EnforcedStyle: always_true
Metrics/AbcSize:
  Max: 25
Metrics/MethodLength:
  Max: 13
Metrics/BlockLength:
  Enabled: false
Lint/SuppressedException:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Enabled: true
  Exclude:
    - 'spec/**/*'
Lint/RaiseException:
  Enabled: true
Layout/LineLength:
  Max: 100
  IgnoredPatterns: ['\A#']
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
RSpec/DescribeClass:
  Exclude:
    - 'spec/features/*'
RSpec/FilePath:
  Exclude:
    - 'spec/graphql/**/*'
RSpec/NestedGroups:
  Max: 6
AllCops:
  Exclude:
    - 'bundle/**/*'
    - '.bundle/**/*'
    - 'bin/setup'
    - 'bin/yarn'
    - 'bin/webpack'
    - 'bin/webpack-dev-server'
    - 'config/initializers/simple_form.rb'
    - 'db/schema.rb'
    - 'db/migrate/20180521120705_devise_create_users.rb'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
